#!/bin/bash
root=$(dirname $(readlink -f $0))
curl=$(which curl)
for id in $($curl -s http://babe.1626.com/feed | grep -o 'http://babe.1626.com/pages/[[:digit:]]\+' | awk -F'/' '{print $5}')
do
	[ ! -d "$root/$id" ] && echo "fetching id=$id ..." >&2 && $root/babe -n $id
done
