#!/usr/bin/env perl
# author: jianingy.yang@gmail.com

use strict;
use warnings;

my $expr = $ARGV[0];

unless ($expr) {
	print STDERR "Usage: $0 CIDR\n";
	print STDERR "Example: \n";
	print STDERR "    $0 192.168.16.0/24 \n";
	print STDERR "    $0 192.168.16.0/23 \n";
	print STDERR "\n";
	exit 0;
}

my ($ip, $cidr) = split /\//, $expr;
my @decimals = split /\./, $ip;

die "Please use a CIDR format IP address"
	unless @decimals == 4 && defined($cidr) && $cidr > -1 && $cidr < 33;

my $addr = 0;
foreach(@decimals) {
	$addr <<= 8;
	$addr |= $_;
}

my $base_addr = $addr & (4294967295 << (32 - $cidr));
my $brd_addr = $addr | (4294967295 >> $cidr);
my (@base, @brd);
foreach (@decimals) {
	unshift @base, $base_addr & 0xFF;
	unshift @brd, $brd_addr & 0xFF;
	$base_addr >>= 8;
	$brd_addr >>= 8;
}
print join(".", @base)."-".join(".", @brd)."\n";
