#!/bin/bash
#author: jianingy.yang@gmail.com

route=$(which 2>/dev/null /usr/local/sbin/route /usr/sbin/route /sbin/route /usr/local/bin/route /usr/bin/route /bin/route | head -1)
awk '/^0\.0\.0\.0/{print $NF;exit}' <($route -n)
