#!/bin/bash
# author: jianingy.yang@gmail.com
route=$(which 2>/dev/null /usr/local/sbin/route /usr/sbin/route /sbin/route /usr/local/bin/route /usr/bin/route /bin/route | head -1)
ip=$(which 2>/dev/null /usr/local/sbin/ip /usr/sbin/ip /sbin/ip /usr/local/bin/ip /usr/bin/ip /bin/ip | head -1)
[ -z "$route" ] && echo 2>/dev/null "$0: route command not found" && exit 255
[ -z "$ip" ] && echo 2>/dev/null "$0: ip command not found" && exit 255
device=$(awk '/^0.0.0.0/ { print $NF; exit}' <($route -n))
#exec awk '$1 ~ /inet$/ && $NF ~ /'$device'$/ {print $2}' <($ip addr show dev $device)
exec awk '$1 ~ /inet$/ && $NF ~ /'$device'$/ {if ($2 ~ /\/[0-9]+/) {print $2} else {print $2"/32"}}' <($ip addr show dev $device)
