#!/bin/bash
# reuse existing ssh-agent
# author: Jianing Yang <jianingy.yang@gmail.com>

# find if ssh-add and ssh-agent exists
for prog in ssh-add ssh-agent; do
    which $prog >/dev/null || exit
done

for SSH_AUTH_SOCK in /tmp/ssh-*/agent.*; do
    [ -S $SSH_AUTH_SOCK ] && ssh-add -l &>/dev/null && echo export SSH_AUTH_SOCK=$SSH_AUTH_SOCK && exit 0 
done

# try again by prompting user to input passpharses.
create_new_agent=1
for SSH_AUTH_SOCK in /tmp/ssh-*/agent.*; do
    if [ -S $SSH_AUTH_SOCK ]; then
        create_new_agent=0
        ssh-add || continue
        ssh-add -l &>/dev/null && echo export SSH_AUTH_SOCK=$SSH_AUTH_SOCK && exit 0
    fi
done

# create new ssh-agent and run again
# echo "no avaiable ssh-agent, starting a new one" >&2
if [ $create_new_agent -eq 1 ]
then
    ssh-agent &>/dev/null
    exec $0 $@
fi

exit 1

# vim: ts=4 sw=4 et ai
